---
config:
    theme: base
---
sequenceDiagram
    participant User as User
    participant Browser as React Browser
    participant WS as WebSocket Server
    participant Car as IoT Car

    Car->>WS: Connect to WebSocket
    Browser->>WS: Connect to WebSocket
    
    User->>Browser: Clicks control button (move/LED/buzzer)
    Browser->>WS: Send JSON command
    WS->>Car: Forward JSON command
    Car->>Car: Process and execute command